FROM debian:9.8-slim

RUN mkdir -p /opt/cni/bin

FROM scratch

LABEL maintainer "Casey Davenport <casey@tigera.io>"

ADD bin/amd64/ /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/calico"]
